### PR TITLE
fix int set

### PR DESCRIPTION
**Pull request by bung87**
pls also bump new version , as its important package.

### CODE REVIEW

**Comment by jangko** [comment]
nope, the fix should be in the compiler. not here

**Comment by bung87** [comment]
I dont think there's exists rules followed, can the compiler implicitly convert to int16 set and implicitly convert the int to int16?

**Comment by jangko** [comment]
that also should be discussed over there in the compiler domain, not here

**Comment by bung87** [comment]
ok then, get another idea.

**Pull request closed without merging**
